#!/bin/bash
skypeforlinux

while true; do
    if ! pgrep -x "skypeforlinux" > /dev/null; then
        sleep 0.5
        if ! pgrep -x "skypeforlinux" > /dev/null; then
            break;
        fi
    fi
    sleep 1
done
